### ISSUE TITLE
Build fails (with recent EUMM?)

### ISSUE THREAD

**Issue by eserte** [powerman/perl-Crypt-MatrixSSL3#30] opened 2016-05-04 19:39 UTC
I see build failures on smoker machines where Crypt-MatrixSSL3-v3.7.6 formerly built and tested OK. Excerpt of the log:
```
cc -c  -I. -Iinc/matrixssl-3-7-2b-open -Iinc/matrixssl-3-7-2b-open/crypto -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Os -Wp,-w -fomit-frame-pointer -fPIC -I./ -I../ -O2   -DVERSION=\"v3.7.6\" -DXS_VERSION=\"v3.7.6\" -fPIC "-I/opt/perl-5.18.2t/lib/5.18.2/x86_64-linux-thread-multi/CORE"  -DUSE_TLS_RSA_WITH_AES_128_CBC_SHA -DUSE_TLS_RSA_WITH_AES_256_CBC_SHA -DUSE_TLS_RSA_WITH_AES_128_CBC_SHA256 -DUSE_TLS_RSA_WITH_AES_256_CBC_SHA256 -DUSE_TLS_RSA_WITH_AES_128_GCM_SHA256 -DUSE_TLS_RSA_WITH_AES_256_GCM_SHA384 -DUSE_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA -DUSE_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA -DUSE_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 -DUSE_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 -DUSE_TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 -DUSE_TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 -DUSE_TLS_DHE_PSK_WITH_AES_256_CBC_SHA -DUSE_TLS_DHE_PSK_WITH_AES_128_CBC_SHA -DUSE_TLS_DHE_RSA_WITH_AES_256_CBC_SHA -DUSE_TLS_DHE_RSA_WITH_AES_128_CBC_SHA -DUSE_TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 -DUSE_TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 -DUSE_AES -DUSE_AES_GCM -DUSE_3DES -DUSE_DES -DUSE_ARC4 -DUSE_RC2 -DUSE_SHA1 -DUSE_SHA256 -DUSE_SHA384 -DUSE_SHA512 -DUSE_MD5 -DUSE_HMAC -DUSE_ECC -DUSE_DH -DUSE_RSA -DUSE_X509 -DUSE_BASE64_DECODE -DUSE_CERT_PARSE -DUSE_FULL_CERT_PARSE -DUSE_PRIVATE_KEY_PARSING -DMATRIX_USE_FILE_SYSTEM -DUSE_CLIENT_SIDE_SSL -DUSE_SERVER_SIDE_SSL -DUSE_TLS -DUSE_TLS_1_1 -DUSE_TLS_1_2 -DDISABLE_SSLV3 -DUSE_STATELESS_SESSION_TICKETS -DENABLE_SECURE_REHANDSHAKES -DENABLE_TLS_FALLBACK_SCSV -DREQUIRE_SECURE_REHANDSHAKES -DENABLE_CERTIFICATE_STATUS_REQUEST -DENABLE_SIGNED_CERTIFICATE_TIMESTAMP -DUSE_ALPN -DENABLE_FALSE_START -DUSE_BEAST_WORKAROUND -DUSE_CLIENT_AUTH -DSERVER_CAN_SEND_EMPTY_CERT_REQUEST -DSERVER_WILL_ACCEPT_EMPTY_CLIENT_CERT_MSG -DUSE_PKCS5 -DUSE_PKCS8 -DUSE_PKCS12 -DPS_PUBKEY_OPTIMIZE_FOR_FASTER_SPEED -DPS_AES_IMPROVE_PERF_INCREASE_CODESIZE -DPS_3DES_IMPROVE_PERF_INCREASE_CODESIZE -DPS_MD5_IMPROVE_PERF_INCREASE_CODESIZE -DPS_SHA1_IMPROVE_PERF_INCREASE_CODESIZE -DLINUX -DPOSIX -DPSTM_64BIT  MatrixSSL3.c 
rm -f blib/arch/auto/Crypt/MatrixSSL3/MatrixSSL3.so
cc  -shared -O2 -L/usr/local/lib -fstack-protector -o blib/arch/auto/Crypt/MatrixSSL3/MatrixSSL3.so  inc/matrixssl-3-7-2b-open/core/corelib.o inc/matrixssl-3-7-2b-open/core/memset_s.o inc/matrixssl-3-7-2b-open/core/POSIX/osdep.o inc/matrixssl-3-7-2b-open/crypto/digest/hmac.o inc/matrixssl-3-7-2b-open/crypto/digest/md2.o inc/matrixssl-3-7-2b-open/crypto/digest/md4.o inc/matrixssl-3-7-2b-open/crypto/digest/md5.o inc/matrixssl-3-7-2b-open/crypto/digest/sha1.o inc/matrixssl-3-7-2b-open/crypto/digest/sha224.o inc/matrixssl-3-7-2b-open/crypto/digest/sha256.o inc/matrixssl-3-7-2b-open/crypto/digest/sha384.o inc/matrixssl-3-7-2b-open/crypto/digest/sha512.o inc/matrixssl-3-7-2b-open/crypto/hardware/aesni.o inc/matrixssl-3-7-2b-open/crypto/keyformat/asn1.o inc/matrixssl-3-7-2b-open/crypto/keyformat/base64.o inc/matrixssl-3-7-2b-open/crypto/keyformat/x509.o inc/matrixssl-3-7-2b-open/crypto/math/pstm.o inc/matrixssl-3-7-2b-open/crypto/math/pstm_montgomery_reduce.o inc/matrixssl-3-7-2b-open/crypto/math/pstm_mul_comba.o inc/matrixssl-3-7-2b-open/crypto/math/pstm_sqr_comba.o inc/matrixssl-3-7-2b-open/crypto/prng/prng.o inc/matrixssl-3-7-2b-open/crypto/prng/yarrow.o inc/matrixssl-3-7-2b-open/crypto/pubkey/dh.o inc/matrixssl-3-7-2b-open/crypto/pubkey/ecc.o inc/matrixssl-3-7-2b-open/crypto/pubkey/pkcs.o inc/matrixssl-3-7-2b-open/crypto/pubkey/pubkey.o inc/matrixssl-3-7-2b-open/crypto/pubkey/rsa.o inc/matrixssl-3-7-2b-open/crypto/symmetric/aes.o inc/matrixssl-3-7-2b-open/crypto/symmetric/aesGCM.o inc/matrixssl-3-7-2b-open/crypto/symmetric/arc4.o inc/matrixssl-3-7-2b-open/crypto/symmetric/des3.o inc/matrixssl-3-7-2b-open/crypto/symmetric/idea.o inc/matrixssl-3-7-2b-open/crypto/symmetric/rc2.o inc/matrixssl-3-7-2b-open/crypto/symmetric/seed.o inc/matrixssl-3-7-2b-open/matrixssl/cipherSuite.o inc/matrixssl-3-7-2b-open/matrixssl/dtls.o inc/matrixssl-3-7-2b-open/matrixssl/hsHash.o inc/matrixssl-3-7-2b-open/matrixssl/matrixssl.o inc/matrixssl-3-7-2b-open/matrixssl/matrixsslApi.o inc/matrixssl-3-7-2b-open/matrixssl/prf.o inc/matrixssl-3-7-2b-open/matrixssl/psk.o inc/matrixssl-3-7-2b-open/matrixssl/sslDecode.o inc/matrixssl-3-7-2b-open/matrixssl/sslEncode.o inc/matrixssl-3-7-2b-open/matrixssl/sslv3.o inc/matrixssl-3-7-2b-open/matrixssl/tls.o MatrixSSL3.o  \
	   -lpthread   \
	  
cc: error: inc/matrixssl-3-7-2b-open/core/corelib.o: No such file or directory
cc: error: inc/matrixssl-3-7-2b-open/core/memset_s.o: No such file or directory
cc: error: inc/matrixssl-3-7-2b-open/core/POSIX/osdep.o: No such file or directory
cc: error: inc/matrixssl-3-7-2b-open/crypto/digest/hmac.o: No such file or directory
...
cc: error: inc/matrixssl-3-7-2b-open/matrixssl/sslv3.o: No such file or directory
cc: error: inc/matrixssl-3-7-2b-open/matrixssl/tls.o: No such file or directory
make: *** [blib/arch/auto/Crypt/MatrixSSL3/MatrixSSL3.so] Error 1
```
It seems that this happens with newer ExtUtils::MakeMaker versions (e.g. 7.14) (@bingos: FYI)

**Comment by powerman** [comment] 2016-05-04 20:18
@vonydev can you please check this?

**Comment by vonydev** [comment] 2016-05-10 09:41
Hello. The issue is resolved in the latest PR. +some more fixes & features.
Let me know if it works for you.
Sorry for the delay - very busy atm.

**Comment by eserte** [comment] 2016-05-10 17:57
I tried commit d079d1bc7975f9b421f2f8caf3f4ca357210282d on a Debian/jessie system with perl 5.22.2 and EUMM 7.16, and compilation & tests were OK.

**Comment by vonydev** [comment] 2016-05-10 17:59
Nice. Thank you.

**Closed** 2016-05-10 19:33 UTC
